"""init

Revision ID: 518ba158c087
Revises:
Create Date: 2025-02-16 18:08:25.720768

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "518ba158c087"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lac", sa.Integer(), nullable=True),
        sa.Column("cellid", sa.Integer(), nullable=True),
        sa.Column("eci", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "(lac is not null and eci is null) or (lac is null and cellid is null and eci is not null)"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("location")
    # ### end Alembic commands ###
